settings:
  model_path: models/yolov8x_trained.pt
  input_video_path: data/input/08fd33_4.mp4
  output_path: data/output
  confidence_threshold: 0.25
  iou_threshold: 0.7
  stub_path: stubs/track_stubs.pkl
